version: "2"
run:
  timeout: 3m
linters:
  enable:
    - errcheck
    - govet
    - dogsled
    - gocritic
    - staticcheck
    - unused
    - unparam
    - ineffassign
    - misspell
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: "internal/cmd/.*\\.go"
        linters:
          - unparam
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hagatasdelus/babbr
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
