name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Relase
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Cross-build artifacts
        run: make cross
      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./goxz/*
          name: Release ${{ github.ref_name }}
